### ISSUE TITLE
Adding to an existing website can cause ID collisions

### ISSUE THREAD

**Issue by fredden** [fooman/sameorderinvoicenumber-implementation-m2#1]
We had a problem when we installed this module on a website with existing orders/invoices/credit memos. Because the order/invoice/shipment/credit-memo numbers did not already line up neatly, we were unable to create invoices nor shipments for existing orders, and new orders paid for during checkout (ie, with an online payment method) were not marked as paid in Magento.

# Steps to reproduce
Note that these steps are for creating a collision for shipments, but the same problem can be trivially created for invoices & credit memos too.

1. developer: Install Magento 2 (tested with the `2.4-develop` branch at 6204718e0fc6c5fb5862de4ae8807c75031946e7)
1. admin: Create a product (or install the sample data) with a large quantity, or multiple products. (We need to purchase at least three items.)
1. frontend: Purchase at least two products. (These can be qty=2 of the same product for ease, but different products work too.) This is **order `#000000001`**.
1. admin: If the order is not yet paid, create an invoice (for the full order). This is **invoice `#000000001`**.
1. admin: Create a shipment for one product only. This is **shipment `#000000001`**.
1. admin: Create a shipment for the balance of the order. This is **shipment `#000000002`**.
1. developer: Install `fooman/sameorderinvoicenumber-m2` with composer. (`composer install fooman/sameorderinvoicenumber-m2 && bin/magento setup:upgrade`)
1. frontend: Place another order. Products / quantity does not matter here. This is **order `#000000002`**.
1. admin: If the order is not yet paid, create an invoice (for the full order). This is **invoice `#000000002`**.
1. admin: Create a shipment for the second order.

# Expected result
A shipment is created for order `#000000002`.

# Actual result
An error is shown in the admin saying "Unique constraint violation found".

<details><summary>Screen-shot of error message</summary>

![Screenshot_2021-11-25_13-53-21](https://user-images.githubusercontent.com/334786/143453799-b213466a-ac1b-4211-8518-5c037017ee99.png)

</details>

**Comment by fooman** [comment]
@fredden I'll close this one for the moment until more details can be added.

My gut feeling here would be that the issue would likely occur without extension as well and/or required some previous customisations around numbering.

Generally speaking adding this extension is safe as the sequence numbers for invoices, shipments and creditmemos are lower than order numbers. When adding the extension the numbers for invoices, shipments and creditmemos would jump ahead. Any collisions would require some other prior customisation.

**Comment by fredden** [comment]
Thanks. We definitely had collisions on a production website when we installed this module. I'll find details and try to recreate the scenario in a controlled environment. I'll update here when I have more information to share.

**Comment by fredden** [comment]
I've been able to reproduce this on the `2.4-develop` branch of Magento Open Source. I have updated the description of this issue with steps to reproduce from a blank installation.

@fooman please can you reopen this; I don't seem to have permissions to do this.

**Comment by fooman** [comment]
hey @fredden thanks for the detailed write up. Indeed when using multiple invoices/shipments on orders prior to installing an extension this can lead to the sequences overlapping.

The way to work around this would be:
a.) use the prefix this extension provides, so 9. becomes I-000000002
b.) bump the order number to be higher that the last invoice/shipment number. Either manually directly in the DB or something like our Order Number Customiser extension.

**Comment by fooman** [comment]
I have updated the unit tests to pass after your changes but otherwise your PR looked good to go. I have released it as version [v3.0.12](https://github.com/fooman/sameorderinvoicenumber-m2/releases/tag/v3.0.12).

Thanks again.
